"""migrate onto Lizzy's computer

Revision ID: 1c183a03504e
Revises: 78daaa790a20
Create Date: 2026-04-30 12:05:17.667087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c183a03504e'
down_revision = '78daaa790a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    with op.batch_alter_table('org', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_name'))

    op.drop_table('org')
    op.drop_table('tag_pair')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_pair',
    sa.Column('org_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('org_id', 'tag_id')
    )
    op.create_table('org',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('website', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), nullable=False),
    sa.Column('address1', sa.VARCHAR(length=64), nullable=False),
    sa.Column('address2', sa.VARCHAR(length=64), nullable=False),
    sa.Column('city', sa.VARCHAR(length=32), nullable=False),
    sa.Column('state', sa.VARCHAR(length=32), nullable=False),
    sa.Column('published', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_name'), ['name'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
