"""initial

Revision ID: 78daaa790a20
Revises: 
Create Date: 2026-04-24 14:50:18.143199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78daaa790a20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('website', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('address1', sa.String(length=64), nullable=False),
    sa.Column('address2', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_name'), ['name'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_pair',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('org_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_pair')
    op.drop_table('tag')
    with op.batch_alter_table('org', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_name'))

    op.drop_table('org')
    # ### end Alembic commands ###
